Controllers/KayıtOlController.cs
using MvcYemek.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcYemek.Controllers
{
    public class KayıtOlController : Controller
    {
        MvcContext db = new MvcContext();
        // GET: KayıtOl
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Kullanici k)//HttpPostedFileBase ResimKayıt
        {


            k.ResimID = 1010;
            k.KayıtTarihi = DateTime.Now;         
            db.Kullanici.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index", "GirisYap");
        }
       
    }
}

Views/KayıtOl/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Weach | Kayıt Ol</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="/Content/Lte/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/Content/Lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/Content/Lte/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a href="/Home/Index"><b>Weach</b>Yapım</a>
        </div>

        <div class="card">
            <div class="card-body register-card-body">
                <p class="login-box-msg"></p>



                @using (Html.BeginForm("Index", "KayıtOl", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="Ad" placeholder="Adınız">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="Soyad" placeholder="Soyadınız">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="KullaniciAdi" placeholder="Kullanıcı adınız">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="email" class="form-control" name="Eposta" placeholder="Eposta Adresiniz">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="Sifre" placeholder="Şifreniz">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Tekrardan şifrenizi giriniz">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>

                    @*<div class="form-group">
                        <label for="exampleInputFile" class="input__label">Kullanıcı Resmini Seç </label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-control" name="ResimKayıt" id="exampleInputFile" value="" />
                                <label class="" for="exampleInputFile"></label>
                            </div>
                        </div>
                    </div>*@


                    @*<div class="form-group">
                <label for="exampleInputFile">Resminizi Seçiniz :</label>
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-control" name="Resim" id="exampleInputFile" value="" />
                        <label class="" for="exampleInputFile"></label>
                    </div>
                </div>
            </div>*@

                    <div class="row">
                        <div class="col-8 mt-2">
                            <a href="/GirisYap/Index" class="text-center">Zaten üyeliğim var</a>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" name="btnKayitOl" class="btn btn-primary btn-block ">Kayıt Ol</button>
                        </div>
                        <!-- /.col -->
                    </div>

                }








            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="/Content/Lte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/Content/Lte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/Content/Lte/dist/js/adminlte.min.js"></script>
</body>
</html>